### ISSUE TITLE
ui-box vs. glamor-jsxstyle vs. jsxstyle perf?

### ISSUE THREAD

**Issue by jaredpalmer** [segmentio/ui-box#15]
Any benchmarks or demos available?

**Comment by Rowno** [comment]
We already had a benchmark for validating internal perf improvements but I've added one for glamor/jsxstyle too. Here are the results:
```
Box
✔ 7,641 ops/sec ±2.92% (58 runs sampled)
glamor/jsxstyle
✔ 4,469 ops/sec ±2.42% (55 runs sampled)
```

You can run the benchmark yourself with `yarn run benchmark`.
