### ISSUE TITLE
Feat. Request: Support css grid

### ISSUE THREAD

**Issue by Flaque** [segmentio/ui-box#21]
Display can support grid at the moment, but not other grid css properties like `grid-template-columns`:

```jsx
<Box display="grid" /> // Yup
<Box gridTemplateColumns="25% 25% 25% 25%" display="grid"/> // Nope
```

Full list of props:
 
- [ ] grid-template-column  
- [ ] grid-template-rows
- [ ] grid-column-start
- [ ] grid-column-end 
- [ ] grid-row-start
- [ ] grid-row-end
- [ ] grid-column
- [ ] grid-row
- [ ] grid-area
- [ ] grid-template-areas
- [ ] grid-template
- [ ] grid-gap
- [ ] place-self
- [ ] place-items
- [ ] align-content
- [ ] place-content
- [ ] grid-auto-columns
- [ ] grid-auto-rows  
- [ ] grid-auto-flow
- [ ] grid

**Comment by Rowno** [comment]
I've released [1.4.0](https://github.com/segmentio/ui-box/releases/tag/v1.4.0) which adds CSS Grid support.
