### ISSUE TITLE
Add TypeScript declarations

### ISSUE THREAD

**Issue by robinschuster** [segmentio/ui-box#24]
As a React developer, this library seems like a perfect baseline library to build upon, as it solves `css-in-js` in a sophisticated way.

However, what keeps me from using it in favor of other `css-in-js` approaches is the lack of TypeScript declarations. 

In `jss`, i have TypeScript autocompletition and type checking shouting at me if i try to set an invalid CSS-property.

Please add TypeScript (and maybe flow) declaration files to this project.

**Comment by Rowno** [comment]
Sorry, I don't know how to write or maintain TypeScript declaration files. You're welcome to open a pull request adding them though.

**Comment by mshwery** [comment]
Starting some initial work on this here: https://github.com/segmentio/ui-box/pull/27

**Comment by nettofarah** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31750

**Comment by peduarte** [comment]
Is this done?

**Comment by mshwery** [comment]
For practical purposes, yes @peduarte !

There are initial type defs released under `@types/ui-box`, but there is also work to migrate ui-box fully over to TypeScript: #28

**Comment by peduarte** [comment]
Awesome!

**Comment by mshwery** [comment]
This is going to be in the next major release. We'll continue making improvements (like generic type signatures for getting `is` props enforcement/autocompletion).

Thank you @Rowno @nettofarah @jfmaggie for your contribution to make this happen! Next up, `evergreen-ui` :)
