### ISSUE TITLE
Support createRef refs for innerREf

### ISSUE THREAD

**Issue by mifi** [segmentio/ui-box#30]
https://reactjs.org/docs/refs-and-the-dom.html#creating-refs

This is used by useRef in the new React Hooks too.

Now it crashes with `innerRef is not a function` [here](https://github.com/segmentio/ui-box/blob/master/src/box.js#L51)

**Comment by Rowno** [comment]
Ah, good point. I'll add it to the TODO list.

**Comment by mshwery** [comment]
This should be supported in recent versions.
