### ISSUE TITLE
Relatively large for use in static sites

### ISSUE THREAD

**Issue by tj** [segmentio/ui-box#36]
Not a huge problem really in practice but 75kb is a little heavy for use in sites. I'm not sure anything could be done to shrink it down though unless some changes were made to the enhancers etc. Might come back and investigate this later, I'm not sure I want to use React for static sites it's pretty bulky

**Comment by tj** [comment]
nvm, not going to use React for static stuff

**Comment by mshwery** [comment]
Not sure where you are seeing 75kb.

<img width="279" alt="Screen Shot 2019-06-02 at 1 23 12 PM" src="https://user-images.githubusercontent.com/710752/58765539-a20e7f80-8539-11e9-9a04-5af26b3a1fcb.png">

**Comment by aleclarson** [comment]
BundlePhobia is reporting 10.8kb min+gzip. 😞 

https://bundlephobia.com/result?p=ui-box@4.1.0

**Comment by mshwery** [comment]
Yep, my comment from 2019 is wrong! size-limit was incorrectly configured and wasn't reporting the true size

**Comment by aleclarson** [comment]
I reduced it to 7.13kb min+gzip by removing `prop-types` support: https://github.com/aleclarson/ui-box/commit/da4da61399f9658dd00fa56a4327fc45b2b6fc84

Who needs it when you have TypeScript 😄
