### ISSUE TITLE
Add support for verticalAlign

### ISSUE THREAD

**Issue by calumbrodie** [segmentio/ui-box#37]
The css property 'https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align' is currently unsupported

**Comment by zartdinov** [comment]
OMG! Where is verticalAlign?

**Comment by mshwery** [comment]
Should be fairly straightforward to add that! PRs welcome of course :) 

Or, if not, we can try to get to it soon! // cc @colinlohner

**Comment by zartdinov** [comment]
OK, I will try ;)

**Comment by Rowno** [comment]
Looks like the `verticalAlign` property was released in [v4.1.0](https://github.com/segmentio/ui-box/releases/tag/v4.1.0).
