### ISSUE TITLE
Integrating `ui-box` styles in Babel pipeline

### ISSUE THREAD

**Issue by haffmaestro** [segmentio/ui-box#49]
Was looking at using ui-box in my project, but came up against needing to extract the styles into its own stylesheet, and then supplying that to our build pipeline.

Not asking you to build this, just if you've already thought about it, what direction would you recommend me taking it in?

Regardless, great work on this component + evergreen, it's inspired my thinking a lot.

**Comment by mshwery** [comment]
I believe [`extractStyles`](https://github.com/segmentio/ui-box/#extractstyles) is what you are looking for! Would that work for you?

**Comment by mshwery** [comment]
Let us know if `extractStyles` doesn't solve your use case! We'd love to hear more. I'm going to close this for now.
