### ISSUE TITLE
1.0.0 changes

### ISSUE THREAD

**Issue by Rowno** [segmentio/ui-box#8]
## Breaking changes
- `boxSizing` now defaults to `border-box`.
- These properties now only accept a single value. e.g: `margin="20px 10px"` won't work, instead you should use `marginY="20px" marginX="10px"`.
  - `margin`
  - `marginX` 
  - `marginY`
  - `padding`
  - `paddingX`
  - `paddingY`
  - `borderRadius`
  - `borderColor`
  - `borderStyle`
  - `borderWidth`
- `splitWrapperProps` has been renamed to `splitBoxProps`.
- `splitProps` and `splitBoxProps` now return `{ matchedProps, remainingProps }`.
- `enhancerGroup.keysPropTypes` has been removed.
- `enhancerGroup.parseProps` has been changed to `enhancerGroup.propEnhancers` which has individual methods for each prop that take a value and return `{ className, css }`.

Enhancer groups are the `dimensions`, `spacing`, etc exports.

## New features
- Add `list-style` property support.
- ~7.5x faster rendering from the cache.
- Majorly improved cache reuse (each prop+value combo is cached separately).
- Server-side rendering support.
- Lots of tests!
- Each of the enhancer groups now contain `propTypes`, `propAliases` and `propEnhancers` properties.
- `propTypes` is now exported (object of all the `propTypes`).
- `propNames` is now exported (array of all the prop names).
- `propAliases` is now exported (object of all the prop aliases).
- `propEnhancers` is now exported (object of all the prop enhancers).

## Deprecations

The `css` prop and `css` export have been deprecated in favor of importing glamor directly and will be removed in the next major release.

**Comment by jeroenransijn** [comment]
## splitProps signature change

Currently `splitProps` return `{ matchedProps, restProps }` which has shown a little confusing. `v1.0.0` should move towards returning `{ matchedProps, remainingProps }`.
